name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Login to registry
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login \
            -u ngalayko \
            -p ${DOCKER_PASSWORD}

    - name: Build images
      run: |
        docker build \
            -t ngalayko/bazel-action:0.29.0 \
            --build-arg BAZEL_VERSION=0.29.0 \
            .

    - name: Push images
      run: |
        docker push ngalayko/bazel-action:0.29.0
