name: ci

on:
  push:
    branches-ignore:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: build
      run: |
        docker build \
            -t ngalayko/bazel-action:0.29.0 \
            --build-arg bazel_version=0.29.0 \
            .
